services:
  zookeeper1:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_CREATE_TOPIC: "my_topic:1:3"
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: Kafka_Monitor
    restart: "no"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    ports:
      - 9000:9000
    depends_on:
      - kafka

  app:
    image: dc_api:1.0
    container_name: spring-app
    depends_on:
      - kafka
    ports:
    - "8081:8081"



#  docker compose -f dockerâ€”compose.yml up -d
#  docker-compose up -d