
logging:
  level:
    org.apache.kafka: OFF
    org.springframework: OFF
    org.apache: OFF

dev:
  bootStrap-server: localhost:9092
server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      bootstarp-servers: kafka:29092
      group-id: "Group1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstarp-servers: kafka:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer