server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstarp-servers: localhost:9092
      group-id: "Group1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstarp-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer